### ISSUE TITLE
Main writethedocs page still lists 2015 NA conference under Upcoming Events

### ISSUE THREAD

**Issue by tanafranko** [writethedocs/www-old#29]
Maybe this conflicts with some of the other feedback that's incoming about the page, but the 2015 North America conference should probably be removed from the top of Upcoming Events on http://www.writethedocs.org/

**Comment by mbuttler** [comment]
This is pretty low hanging fruit, though, and is an easy enough fix. One sec...

**Comment by mbuttler** [comment]
It's a pretty simple change, but it makes a pretty big difference. What do you think?

**Comment by mbuttler** [comment]
Fixed in #30
