### ISSUE TITLE
How is this site rendered?

### ISSUE THREAD

**Issue by RichardLitt** [writethedocs/www-old#36]
> We develop documentation on a dev branch, which is rendered at http://writethedocs-www.readthedocs.org/en/dev/.

I'm not sure this is true. `dev` is 26 commits behind master. [This page](http://conf.writethedocs.org/) at least isn't being rendered from the `master` branch, as the conferences are out of date. 

How is development working?

**Comment by ericholscher** [comment]
We now use Sphinx for the site rendering. You can build it locally as referenced in the README.

**Comment by ericholscher** [comment]
We mostly work on the master branch, and use dev just for occasional rendering checks.

**Comment by RichardLitt** [comment]
Readme probably updated since this comment. Cheers.
