### ISSUE TITLE
No link to videos

### ISSUE THREAD

**Issue by tommorris** [writethedocs/www-old#37]
There doesn't seem to be a link to conference videos from the website. It might make it easier for people to enjoy the content if they could get to it—and it might make people interested in going to future WriteTheDocs conferences and meetups.

**Comment by ericholscher** [comment]
Totally. It would be great if you could send a Pull Request to fix this!

Thanks,
Eric

On Sun, Oct 18, 2015 at 2:04 PM, Tom Morris notifications@github.com
wrote:

> There doesn't seem to be a link to conference videos from the website. It
> might make it easier for people to enjoy the content if they could get to
> it—and it might make people interested in going to future WriteTheDocs
> conferences and meetups.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/writethedocs/www/issues/37.

## 

Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by plaindocs** [comment]
I had a vague plan of adding them to them to http://www.writethedocs.org/conf/eu/2015/schedule/ but have not found the time for it.

**Comment by ericholscher** [comment]
This should now be fixed with http://www.writethedocs.org/videos/
