### ISSUE TITLE
The vs the

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www-old#57]
Can we pick one of 
- Write the Docs
- Write The Docs

and stick to it? We've got a mix at the mo. As we use WTD I'd go with second option.

**Comment by ericholscher** [comment]
+1 on "the" -- it's origin is "Read the Docs", so it should mirror it, IMO.

**Comment by alexfornuto** [comment]
+1 for Write the Docs

**Comment by plaindocs** [comment]
I'll look at hooking an rst compatible linter up to travis-ci at some point.
