### ISSUE TITLE
Add roundup blog posts to "Thanks" section of the site

### ISSUE THREAD

**Issue by ericholscher** [writethedocs/www-old#72]
If anyone is looking for a way to contribute back to WTD — it would be great to find links to all the round up blog posts and add them to the main conf website under the "Thanks" section. You can find the page to edit here: https://github.com/writethedocs/www/blob/master/docs/conf/na/2016/index.rst

It should just be a link to the blog posts under a heading like "Write ups from the community".

The `#writethedocs` hashtag on Twitter is probably the best place to find write ups, as well as Google for "write the docs 2016" or similar.

**Comment by singingwolfboy** [comment]
Here's my write-up: https://www.davidbaumgold.com/blog/2016/05/wtd-na-2016/

**Comment by kvantomme** [comment]
We are planning a presentation like the one we did for the Prague event last year, that we can share with all the meetup organisers. We could add that as a recap. Maybe also put the same content into a blogpost. This is last year's presentation: https://docs.google.com/presentation/d/1EJILgaOd-wnToiy1JLyo292gx7fakYziZ5KTN3yrP1U/edit#slide=id.g35f391192_00
