### ISSUE TITLE
Fixing-uping of EU site for launch

### ISSUE THREAD

**Issue by thatdocslady** [writethedocs/www-old#8]
@ericholscher @agjohnson, just throwing these here so we don't forget nuthin':
- Fix toolbar (replace Speakers with Call for Proposals or something)
- Hide "Buy a Ticket" button
- Adjust colors to match EU2014 scheme (or similar)
- Replace top logo with EU dates and location

**Comment by ericholscher** [comment]
Closing this, as it is now the EU conf :)
